server:
  port: 9000

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: event-service
          uri: lb://EVENT-SERVICE/
          predicates:
            Path=/api/event/**
          filters:
            - AuthFilter
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE	/
          predicates:
            Path=/api/reservation/**
          filters:
            - AuthFilter
        - id: RegisterService
          uri: lb://REGISTER-SERVICE/
          predicates:
            Path=/api/register/**
  application:
    name: gateway-api-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka